[package]
name = "godandanime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tvrank = "0.7.4"
scraper = "0.12.0"
reqwest = { version = "0.11.10", features = ["blocking"] }